[project]
name = "autohack"
version = "0.1.0"
description = " highly customizable competitive programming Hack tool written in Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "platformdirs>=4.3.8",
]
