name: Install UPX
description: An action to install UPX for executable compression.

runs:
  using: "composite"

  steps:
    - name: Install UPX (Linux)
      if: env.MATRIX_PLATFORM == 'linux'
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true

    - name: Install UPX (Windows)
      if: env.MATRIX_PLATFORM == 'windows'
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v5.0.2/upx-5.0.2-win64.zip" -OutFile "upx.zip"
        Expand-Archive -Path "upx.zip" -DestinationPath "."
        $upxPath = (Get-ChildItem -Path "." -Name "upx-*" -Directory | Select-Object -First 1)
        $env:PATH = "$PWD\$upxPath;$env:PATH"
        echo "$PWD\$upxPath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install UPX (macOS)
      shell: bash
      if: env.MATRIX_PLATFORM == 'macos'
      run: |
        brew install upx
