name: Build python package
description: A workflow to build a Python package and upload the build artifacts.

runs:
  using: composite

  steps:
  - name: Configure Python environment
    uses: ./.github/actions/prepare-python-env

  - name: Build package
    shell: bash
    run: uv build

  - name: Upload build artifacts
    uses: actions/upload-artifact@v4
    with:
      name: build-artifacts
      path: dist/*
