name: Prepare Python Environment
description: An action to prepare a Python environment for building and testing Python packages.

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --all-groups
