name: Build python package

on:
  workflow_call:
  push:
    paths:
      - .github/workflows/build-python-package.yml

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build python package
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure Python environment
        uses: ./.github/actions/prepare-python-env

      - name: Build package
        run: uv build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/*
