name: Build python package

on:
  workflow_call:
  push:
    paths:
      - .github/workflows/build-python-package.yml

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Configure Python environment
      uses: ./.github/actions/prepare-python-env

    - name: Build package
      run: uv build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/*
